name: flutter_ble_peripheral
description: This plugin enables a device to be set into peripheral mode, and advertise custom
  services and characteristics.
version: 1.2.5
homepage: https://github.com/juliansteenbakker/flutter_ble_peripheral

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.10.0"

# Generating json:  flutter pub run build_runner build --delete-conflicting-outputs

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  lint: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: dev.steenbakker.flutter_ble_peripheral
        pluginClass: FlutterBlePeripheralPlugin
      ios:
        pluginClass: FlutterBlePeripheralPlugin
      macos:
        pluginClass: FlutterBlePeripheralPlugin
      windows:
        pluginClass: FlutterBlePeripheralPluginCApi
