name: flutter_ble_peripheral
description: This plugin enables a device to be set into peripheral mode, and advertise custom
  services and characteristics.
version: 1.1.1
homepage: https://github.com/juliansteenbakker/flutter_ble_peripheral

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.steenbakker.flutter_ble_peripheral
        pluginClass: FlutterBlePeripheralPlugin
      ios:
        pluginClass: FlutterBlePeripheralPlugin
      macos:
        pluginClass: FlutterBlePeripheralPlugin
      windows:
        pluginClass: FlutterBlePeripheralPluginCApi
