on:
  pull_request: 
  push:
    branches:
      - master
      - develop
      
name: Test Flutter
jobs:
  test:
    name: Test Flutter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - uses: actions/setup-java@v1.3.0
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.3.0
      with:
        flutter-version: 'stable'
    - run: flutter pub get
    - run: flutter test
